[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove these redirects as they're causing issues
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"} 