[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

# Use the new Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Include this if you're using Next.js 13.4 or above
    nextConfigDir = "/"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"} 